name: Publish to Maven Central

# create a new release on GitHub to trigger this workflow
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }} # Maven Central username
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} # Maven Central password
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # GPG private key  -----BEGIN PGP PRIVATE KEY BLOCK----- XXXXXXX  -----END PGP PRIVATE KEY BLOCK-----
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # GPG passphrase

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release title
        id: release_title
        run: echo "::set-output name=title::${{ github.event.release.name }}"

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './version.properties'
          property: |
            'example'
          value: |
            "${{ steps.release_title.outputs.title }}"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.properties
        run: |
          NEW_VERSION="${{ steps.release_title.outputs.title }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.properties
          git commit -m "Bump version to $NEW_VERSION"
          git push origin master
