name: Publish to Maven Central

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
          
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build
        run: chmod +x ./gradlew 
      - name: Build and Test
        run: ./gradlew build
      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publish
