name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release title
        id: release_title
        run: echo "::set-output name=title::${{ github.event.release.name }}"

      - name: Update version.properties
        run: |
          VERSION=$(cat version.properties)
          NEW_VERSION="${{ steps.release_title.outputs.title }}" # Use release title as new version
          echo "version=$NEW_VERSION" > version.properties
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.properties
          git commit -m "Bump version to $NEW_VERSION"
          git push origin master
