name: Publish to Maven Central

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Assuming you've stored your GPG private key as a GitHub secret
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # The environment variable for the GPG private key passphrase
      - name: Build
        run: chmod +x ./gradlew
      - name: Build and Test
        run: ./gradlew build


      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # Assuming you've stored your GPG private key as a GitHub secret
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # The environment variable for the GPG private key passphrase
        run: ./gradlew publish